import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { useState } from 'react'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [url, setUrl] = useState("");
  const [url_hash, setUrl_hash] = useState("");
  const [success, setSuccess] = useState(false);
  const [error, setError] = useState(false);
  const [loading, setLoading] = useState(false);

  const handleClick = async () => {
    setLoading(true);
    setSuccess(false);
    setError(false);
    const data = await axios.post('/api/create', {
      url, url_hash
    });

    if(data.status === 200) setSuccess(true);
    else setError(true);
    setLoading(false);

  }

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>SHURL</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <div>
            <input onChange={(e) => setUrl(e.target.value)} value={url} type="text" placeholder='Enter your URL' /> &nbsp;
            <input onChange={(e) => setUrl_hash(e.target.value)} value={url_hash} type="text" placeholder='Enter your URL Hash' /> &nbsp;
            <button onClick={handleClick}>Go !</button>

          </div>
          {loading && <p>Loading . . .</p>}
          {success && <p>URL has been shortened</p>}
          {error && <p>Something Went Wrong</p>}
        </main>
      </div>
    </>
  )
}
